import '../../../models/car_service_request.dart';

// Module 3: the checklist a car-service job starts with, seeded from the
// service type(s) the owner booked. Each entry becomes a row in
// `service_tasks` (is_extra = false, approval = 'included'). The staff ticks
// them off as they work, and anything extra they find on inspection is
// added later as a 'pending' task the owner must approve.
//
// Each type's own line items are set to sum to EXACTLY that type's fixed
// price (CarServiceType.price) - there is no separate transport/admin fee
// added on top, so the checklist's billable total always matches the
// estimate the owner was quoted at booking, with nothing appearing later
// that wasn't part of the original fixed price.

class _SeedTask {
  final String title;
  final String? detail;
  final double price;
  const _SeedTask(this.title, this.price, [this.detail]);
}

const Map<String, List<_SeedTask>> _byType = {
  'general': [
    _SeedTask('Engine oil & filter change', 100,
        'Fully synthetic 5W-40, up to 4 litres'),
    _SeedTask('Air filter inspection & clean', 15),
    _SeedTask('Brake inspection — front & rear', 15),
    _SeedTask('Top up fluids', 15,
        'Coolant, brake, washer and power-steering fluid'),
    _SeedTask('30-point safety check', 15),
  ], // = 160, matches CarServiceType.general.price
  'oilFilter': [
    _SeedTask('Drain used engine oil', 0),
    _SeedTask('Replace oil filter', 30, 'OEM filter'),
    _SeedTask('Refill engine oil', 85, 'Semi-synthetic 5W-40, 4 litres'),
    _SeedTask('Reset service indicator', 0),
    _SeedTask('Visual under-body check', 15),
  ], // = 130, matches CarServiceType.oilFilter.price
  'tyre': [
    _SeedTask('Tyre rotation — 4 wheels', 40),
    _SeedTask('Wheel balancing', 40),
    _SeedTask('Tread depth & pressure check', 0),
    _SeedTask('Wheel alignment check', 70),
  ], // = 150, matches CarServiceType.tyre.price
  'battery': [
    _SeedTask('Battery health & voltage test', 55),
    _SeedTask('Clean terminals & check charging system', 40),
    _SeedTask('Test alternator output', 25),
  ], // = 120, matches CarServiceType.battery.price
  'wash': [
    _SeedTask('Exterior wash & hand dry', 30),
    _SeedTask('Interior vacuum & wipe-down', 35),
    _SeedTask('Tyre shine & glass clean', 15),
  ], // = 80, matches CarServiceType.wash.price
  'inspection': [
    _SeedTask('Full 50-point mechanical inspection', 100),
    _SeedTask('OBD-II diagnostic scan', 50),
    _SeedTask('Brake & suspension check', 35),
    _SeedTask('Written condition report', 15),
  ], // = 200, matches CarServiceType.inspection.price
};

// Rows to insert into `service_tasks` for a new request - one checklist per
// selected service type, concatenated (a booking can cover more than one
// kind of service in the same visit). `id` / `created_at` are generated by
// the database.
List<Map<String, dynamic>> defaultServiceTasks(
  String serviceRequestId,
  List<CarServiceType> types,
) {
  final seeds = <_SeedTask>[
    for (final type in types) ...(_byType[type.name] ?? _byType['general']!),
  ];
  return seeds
      .map((s) => {
            'service_request_id': serviceRequestId,
            'title': s.title,
            'detail': s.detail,
            'price': s.price,
            'is_extra': false,
            'approval': 'included',
          })
      .toList();
}
